services:
  ibm-mq:
    container_name: ibm-mq
    image: ibmcom/mq
    ports:
      - "1414:1414"
      - "9443:9443"
    volumes:
      - ./.docker/20-config.mqsc:/etc/mqm/20-config.mqsc
      - ./tls/ca.crt:/etc/mqm/pki/keys/mykey/ca.crt
      - ./tls/server/server-ca-unencrypted-key.key:/etc/mqm/pki/keys/mykey/tls.key
      - ./tls/server/server-signed.crt:/etc/mqm/pki/keys/mykey/tls.crt
      - ./tls/client/client-signed.crt:/etc/mqm/pki/trust/0/tls.crt
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
