services:
  ibm-mq:
    container_name: ibm-mq
    image: ibmcom/mq
    ports:
      - "1414:1414"
      - "9443:9443"
    volumes:
      - ./.docker/20-config.mqsc:/etc/mqm/20-config.mqsc
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
